spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace

server:
  servlet:
    context-path: /todo
  error:
    whitelabel:
      enabled: false
